import http from "node:http";
import { chromium } from "playwright-core";
import { readFile } from "node:fs/promises";
import path from "node:path";
const ROOT = process.cwd();
const MIME={".html":"text/html",".js":"text/javascript",".css":"text/css",".json":"application/json",".svg":"image/svg+xml",".png":"image/png",".ico":"image/x-icon"};
const server=http.createServer(async(req,res)=>{try{let rel=decodeURIComponent(new URL(req.url,"http://x").pathname);if(rel==="/")rel="/index.html";const fp=path.normalize(path.join(ROOT,rel));const d=await readFile(fp);res.writeHead(200,{"content-type":MIME[path.extname(fp)]||"application/octet-stream"});res.end(d);}catch{res.writeHead(404).end();}});
await new Promise(r=>server.listen(0,"127.0.0.1",r));
const port=server.address().port;
const b=await chromium.launch({executablePath:"/usr/bin/google-chrome",args:["--no-sandbox","--enable-unsafe-swiftshader"]});
const ctx=await b.newContext({viewport:{width:1280,height:800}});
const page=await ctx.newPage();
page.on("pageerror",e=>console.log("PAGEERROR:",e.message,"\n",e.stack));
page.on("console",m=>{if(m.type()==="error")console.log("CONSOLE-ERR:",m.text());});
await page.goto(`http://127.0.0.1:${port}/`,{waitUntil:"load"});
await page.waitForSelector(".pf-screen-title .pf-btn-big:visible");
await page.click(".pf-screen-title .pf-btn-big");
await page.waitForSelector(".pf-screen-play:not([hidden])");
await page.click(".pf-tray .pf-btn-go");
await page.waitForFunction(()=>document.getElementById("pf-phase")?.textContent.includes("Phase: run"));
await page.waitForSelector(".pf-screen-results:not([hidden])",{timeout:20000});
console.log("results h2:",await page.textContent(".pf-screen-results h2"));
await page.click(".pf-screen-results .pf-btn-primary");
await page.waitForTimeout(2000);
console.log("after next chamber, play hidden?",await page.evaluate(()=>document.querySelector('.pf-screen-play')?.hidden));
console.log("objective:",await page.evaluate(()=>document.getElementById('pf-objective')?.textContent));
console.log("screens:",await page.evaluate(()=>Array.from(document.querySelectorAll('.pf-screen')).map(s=>s.className+':hidden='+s.hidden)));
await b.close();await new Promise(r=>server.close(r));
